{% set version = "4.2.3" %}

package:
  name: wxpython
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/w/wxPython/wxPython-{{ version }}.tar.gz
  sha256: 20d6e0c927e27ced85643719bd63e9f7fd501df6e9a8aab1489b039897fd7c01
  patches:
    - patches/0001-linux-gdk-backend.patch
    - patches/0002-allow-cross-compilation.patch
    - patches/0003-Don-t-enable-debug-info-for-all-builds.patch
    - patches/0004-enable-use-of-no_magic-and-install_wx-on-Windows.patch
    - patches/0005-MacOS-no-builtin-3rdparty.patch


build:
  number: 4
  osx_is_app: true  # [osx]
  missing_dso_whitelist:   # [osx]
    - /System/Library/Frameworks/QTKit.framework/Versions/A/QTKit  # [osx]

requirements:
  build:
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - cython                              # [build_platform != target_platform]
    - gnuconfig                           # [unix]
    - make                                # [unix]
    - pkg-config                          # [not win]
    - sip 6.10.0
    - setuptools
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}

  host:
    - python
    - pip
    - attrdict3
    - cython
    - expat               # [linux]
    - gtk3                # [linux]
    - libgl-devel         # [linux]
    - libglx-devel        # [linux]
    - requests
    - setuptools
    - wxwidgets 3.2
    - xorg-xineramaproto  # [linux]
    - xorg-libxfixes      # [linux]
    - xorg-libxext        # [linux]
    - xorg-libxxf86vm     # [linux]
    - xorg-libxdamage     # [linux]
    - xorg-xorgproto      # [linux]
    - zlib                # [linux]
    - liblzma-devel       # [linux]

  run:
    - python
    - python.app         # [osx]
    - gtk3               # [linux]
    - numpy
    - pillow
    - setuptools
    - six
    - typing_extensions  # [py < 311]


test:
  imports:
    - wx

about:
  home: https://wxpython.org/
  license: LGPL-2.0-or-later WITH WxWindows-exception-3.1
  license_family: LGPL
  license_file: LICENSE.txt
  summary: Cross platform GUI toolkit for Python, "Phoenix" version
  description: |
    Welcome to wxPython's Project Phoenix! Phoenix is the improved next-generation
    wxPython, "better, stronger, faster than he was before." This new
    implementation is focused on improving speed, maintainability and
    extensibility. Just like "Classic" wxPython, Phoenix wraps the wxWidgets C++
    toolkit and provides access to the user interface portions of the wxWidgets
    API, enabling Python applications to have a native GUI on Windows, Macs or
    not win systems, with a native look and feel and requiring very little (if any)
    platform specific code.
  doc_url: https://docs.wxpython.org/
  dev_url: https://github.com/wxWidgets/Phoenix

extra:
  recipe-maintainers:
    - ocefpaf
    - constantinpape
    - timsnyder
    - pauldmccarthy
