{% set version = "4.0.3" %}

package:
  name: wxpython
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/w/wxPython/wxPython-{{ version }}.tar.gz
  sha256: 8d0dfc0146c24749ce00d575e35cc2826372e809d5bc4a57bde6c89031b59e75
  patches:
    # Make sure windows builds dont try to use msgfmt.
    - build.py.patch
    - 0001-MacOSX-Use-libc-not-libstdc.patch
    - 0002-MacOSX-Specify-correct-SDK-path-and-version.patch
    - 0003-Don-t-enable-debug-info-for-all-builds.patch
    - 0004-Use-custom-function-for-python_header-checking-on-Da.patch

build:
  number: 1002
  osx_is_app: True  # [osx]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"  # [win]
  missing_dso_whitelist:                                           # [osx]
    - /System/Library/Frameworks/QTKit.framework/Versions/A/QTKit  # [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('gtk2-devel') }}            # [linux]
    - {{ cdt('libpng-devel') }}          # [linux]
    - {{ cdt('libxrender-devel') }}      # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('libXxf86vm-devel') }}      # [linux]
    - {{ cdt('libselinux') }}            # [linux]
    - {{ cdt('libdrm-devel') }}          # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libxau-devel') }}          # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libxfixes-devel') }}       # [linux]
    - {{ cdt('libxext-devel') }}         # [linux]
    - {{ cdt('libxinerama') }}           # [linux]
    - {{ cdt('libxi') }}                 # [linux]
    - {{ cdt('libxcb') }}                # [linux]
    - {{ cdt('libxcursor') }}            # [linux]
    - {{ cdt('libxcomposite') }}         # [linux]
    - {{ cdt('libxdamage-devel') }}      # [linux]
    - {{ cdt('webkitgtk-devel') }}       # [linux]
    - {{ cdt('libsoup-devel') }}         # [linux]
  host:
    - python
    - pip
    - backports.lzma  # [osx]
    - cairo  # [linux]
    - expat  # [not win]
    - gettext  # [not win]
    - glib  # [linux]
    - gst-plugins-base  # [linux]
    - gstreamer  # [linux]
    - gtk2  # [linux]
    - jpeg  # [not win]
    - libglu  # [linux]
    - libiconv  # [osx]
    - libpng  # [not win]
    - libxml2  # [linux]
    - pango  # [linux]
    - pthread-stubs
    - requests
    - setuptools
    - xz  # [not win]
    - zlib  # [not win]
  run:
    - python
    - backports.lzma  # [osx]
    - cairo  # [linux]
    - expat  # [not win]
    - gettext  # [not win]
    - glib  # [linux]
    - gst-plugins-base  # [linux]
    - gstreamer  # [linux]
    - gtk2  # [linux]
    - jpeg  # [not win]
    - libglu  # [linux]
    - libiconv  # [osx]
    - libpng  # [not win]
    - libxml2  # [linux]
    - pango  # [linux]
    - pthread-stubs
    - python.app  # [osx]
    - requests
    - setuptools
    - six
    - xz  # [not win]
    - zlib  # [not win]
    - pypubsub  # [py3k]

test:
  imports:
    - wx
    - wx.lib.pubsub  # [py3k]

about:
  home: https://wxpython.org/Phoenix/
  license: wxWindows Library v3.1
  license_family: LGPL
  # license_file: LICENSE.txt
  summary: Cross platform GUI toolkit for Python, "Phoenix" version
  description: |
    Welcome to wxPython's Project Phoenix! Phoenix is the improved next-generation
    wxPython, "better, stronger, faster than he was before." This new
    implementation is focused on improving speed, maintainability and
    extensibility. Just like "Classic" wxPython, Phoenix wraps the wxWidgets C++
    toolkit and provides access to the user interface portions of the wxWidgets
    API, enabling Python applications to have a native GUI on Windows, Macs or
    not win systems, with a native look and feel and requiring very little (if any)
    platform specific code.
  doc_url: https://wxpython.org/Phoenix/docs/html/index.html
  dev_url: https://github.com/wxWidgets/Phoenix

extra:
  recipe-maintainers:
    - ocefpaf
    - constantinpape
