appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: ZSdvgtKPfA2/aVf15ntNstNPGxxTTJtyV4UbD5uR1S2jjNK+LxE5/riVh8jVQF53vysHmrw+1Coia3TQCqszTVTisLQGJrlzm2O7E7Bk7Cdq8DaKqS4CCIgLw0eQcPVLqjEDZ+cYKJsDtxCJmjf2d0H8rWHtClTrrk9XxD0mT+7mQMKwaHQHtTIjJFkdNGcMH31qC2m0LgMBuHNisU2JaX7AFpO8/ZcYBs0QeY2oF8OUFf6WHICX2dEGh+m13DajaZLB0iLK2MnVvGsb2cS3HRQ+D19ZuMlIiIHdV8z2sq2Eee77gzn/9x1zPSd3aRBxHahRwKNBtBVkoUNDTWGyHcJ72vpCClr0vwvED6L4KHbY0L60Gb26ZT4sS8C6E0BHwIABabx2dsqE79l2U4wu0Ri7T+5zv2G2EGxv8fIcQzDHuz1qPrzoKDNQuwzcgfUlCBc8JJlf5bxrYpTmxmrJTYfWG4WZVHFEiW/bRyVRmPdQAcLQK0bd0j+5hEMTm46RVvPw2TmiO62IHGQSqtWzAq03AjZrs03nQTyJBJdEzdZiO4xJpY9JWShJAN/2AhUc6EqZyF4RrZuU1Orf2NzeeJQiCnZu0WTYhMKnmttHUenS8cgXkOnJ8t3GHjLB6+hGuGrU8DzDIJNPco1LlxvtKZmKTxJCYuGBThIL450cw2I=}
provider:
  win: azure