travis:
  secure:
    BINSTAR_TOKEN: T7VSEp/nf7xPvCAj3HYg9wkr+ARmghQv6wxNLgf6DZ0M9HTB6FUoRnYwG5tPC9NPx6Lb8Y1nMNijc1RBBlxh1D8UY6syis0ej/laKGS5a3Ocz/5lkMt7F7r1+VffRd4urlqNGb5qWmmpWse7I/iQ9IEBY9EQaCLGNQZA/iLinoO3g3Gm/5XKD3TFRjYZR3QgimfMORH6Hp22MX+henFmUVeEShcu62psu/PsnCVtTto+pYuiPRBWsSXXwivlPzPEQE5bbsIqnLSP+XNW04RBapR9eoCJ60URh0fkbXF+dhJMz4WoKwUYQfWkT2iW9PGJTvfECGyZdzYGEhBy3D1FX02ZkG/JEoV2KKg5DqjTwzGlEuafR1KjXkkDMlm66yO7UJUmY0lpxeS9OCCwBgVND/puHtqhyxKKJw8izIG7ZLa8N5oLTgPN9ZcnopodrKsJB5DLlUw75NlEg7DTm7KxIqzW+thCkh5K220bNZ50M+OGriDUzEsJziyhOVT3qkx3cxHjxSyYEZz9a+fttQDhPh/ThmKw9iMVsB7nyHl6nOm/ZO0Rv8Pw3AAZafe7p3tNNv+RnjRqzrHLtME/hmYuDSXXRMsn/TJbW3hXRihx4jLLLLLAyekFf5ic7FNp7nQ45IAuYG06mOYSW2A1kVDLJAb6ssKPNSDKywtujB9Ffbo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
